# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-15 02:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_auto_20160114_0403'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='recurrence_id',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
