# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-15 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_recurrence'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurrence',
            name='dtend',
            field=models.DateTimeField(blank=True, null=True, verbose_name='End'),
        ),
    ]
