# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-16 12:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_auto_20160117_0151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='recurrence_id',
        ),
        migrations.AlterField(
            model_name='event',
            name='all_day',
            field=models.BooleanField(default=False, verbose_name='All day'),
        ),
    ]
