# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-16 12:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_event_remote_calendar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recurrence',
            name='event',
        ),
        migrations.DeleteModel(
            name='Recurrence',
        ),
    ]
