language: python
sudo: false
python: 3.6
before_script: pip install tox

matrix:
  include:
    - env: TOX_ENV=django_111
    - env: TOX_ENV=django_110
    - env: TOX_ENV=coverage
    - env: TOX_ENV=djangolatest
    - env: TOX_ENV=flake
  allow_failures:
    - env: TOX_ENV=djangolatest
    - env: TOX_ENV=flake

script: tox -e $TOX_ENV
