# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-12 07:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pycal', '0002_auto_20160519_0104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='dend',
        ),
        migrations.RemoveField(
            model_name='event',
            name='dstart',
        ),
        migrations.RemoveField(
            model_name='event',
            name='tend',
        ),
        migrations.RemoveField(
            model_name='event',
            name='tstart',
        ),
    ]
